#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_GestionCongee
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="gs_con")]
	public partial class gs_CongeeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void Insertbureau(bureau instance);
    partial void Updatebureau(bureau instance);
    partial void Deletebureau(bureau instance);
    partial void Insertdemande(demande instance);
    partial void Updatedemande(demande instance);
    partial void Deletedemande(demande instance);
    partial void Insertpersonne(personne instance);
    partial void Updatepersonne(personne instance);
    partial void Deletepersonne(personne instance);
    #endregion
		
		public gs_CongeeDataContext() : 
				base(global::Projet_GestionCongee.Properties.Settings.Default.gs_conConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public gs_CongeeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public gs_CongeeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public gs_CongeeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public gs_CongeeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<bureau> bureau
		{
			get
			{
				return this.GetTable<bureau>();
			}
		}
		
		public System.Data.Linq.Table<demande> demande
		{
			get
			{
				return this.GetTable<demande>();
			}
		}
		
		public System.Data.Linq.Table<historique> historique
		{
			get
			{
				return this.GetTable<historique>();
			}
		}
		
		public System.Data.Linq.Table<personne> personne
		{
			get
			{
				return this.GetTable<personne>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bureau")]
	public partial class bureau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nomB;
		
		private EntitySet<personne> _personne;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomBChanging(string value);
    partial void OnnomBChanged();
    #endregion
		
		public bureau()
		{
			this._personne = new EntitySet<personne>(new Action<personne>(this.attach_personne), new Action<personne>(this.detach_personne));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomB", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nomB
		{
			get
			{
				return this._nomB;
			}
			set
			{
				if ((this._nomB != value))
				{
					this.OnnomBChanging(value);
					this.SendPropertyChanging();
					this._nomB = value;
					this.SendPropertyChanged("nomB");
					this.OnnomBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bureau_personne", Storage="_personne", ThisKey="id", OtherKey="id_B")]
		public EntitySet<personne> personne
		{
			get
			{
				return this._personne;
			}
			set
			{
				this._personne.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_personne(personne entity)
		{
			this.SendPropertyChanging();
			entity.bureau = this;
		}
		
		private void detach_personne(personne entity)
		{
			this.SendPropertyChanging();
			entity.bureau = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.demande")]
	public partial class demande : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.DateTime _date_d;
		
		private System.DateTime _date_f;
		
		private string _etat;
		
		private string _certificat;
		
		private int _id_pers;
		
		private string _commentaire;
		
		private System.DateTime _date_demande;
		
		private string _type;
		
		private EntityRef<personne> _personne;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ondate_dChanging(System.DateTime value);
    partial void Ondate_dChanged();
    partial void Ondate_fChanging(System.DateTime value);
    partial void Ondate_fChanged();
    partial void OnetatChanging(string value);
    partial void OnetatChanged();
    partial void OncertificatChanging(string value);
    partial void OncertificatChanged();
    partial void Onid_persChanging(int value);
    partial void Onid_persChanged();
    partial void OncommentaireChanging(string value);
    partial void OncommentaireChanged();
    partial void Ondate_demandeChanging(System.DateTime value);
    partial void Ondate_demandeChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    #endregion
		
		public demande()
		{
			this._personne = default(EntityRef<personne>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_d", DbType="Date NOT NULL")]
		public System.DateTime date_d
		{
			get
			{
				return this._date_d;
			}
			set
			{
				if ((this._date_d != value))
				{
					this.Ondate_dChanging(value);
					this.SendPropertyChanging();
					this._date_d = value;
					this.SendPropertyChanged("date_d");
					this.Ondate_dChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_f", DbType="Date NOT NULL")]
		public System.DateTime date_f
		{
			get
			{
				return this._date_f;
			}
			set
			{
				if ((this._date_f != value))
				{
					this.Ondate_fChanging(value);
					this.SendPropertyChanging();
					this._date_f = value;
					this.SendPropertyChanged("date_f");
					this.Ondate_fChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etat", DbType="VarChar(255)")]
		public string etat
		{
			get
			{
				return this._etat;
			}
			set
			{
				if ((this._etat != value))
				{
					this.OnetatChanging(value);
					this.SendPropertyChanging();
					this._etat = value;
					this.SendPropertyChanged("etat");
					this.OnetatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_certificat", DbType="VarChar(255)")]
		public string certificat
		{
			get
			{
				return this._certificat;
			}
			set
			{
				if ((this._certificat != value))
				{
					this.OncertificatChanging(value);
					this.SendPropertyChanging();
					this._certificat = value;
					this.SendPropertyChanged("certificat");
					this.OncertificatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pers", DbType="Int NOT NULL")]
		public int id_pers
		{
			get
			{
				return this._id_pers;
			}
			set
			{
				if ((this._id_pers != value))
				{
					if (this._personne.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_persChanging(value);
					this.SendPropertyChanging();
					this._id_pers = value;
					this.SendPropertyChanged("id_pers");
					this.Onid_persChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commentaire", DbType="VarChar(255)")]
		public string commentaire
		{
			get
			{
				return this._commentaire;
			}
			set
			{
				if ((this._commentaire != value))
				{
					this.OncommentaireChanging(value);
					this.SendPropertyChanging();
					this._commentaire = value;
					this.SendPropertyChanged("commentaire");
					this.OncommentaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_demande", DbType="Date NOT NULL")]
		public System.DateTime date_demande
		{
			get
			{
				return this._date_demande;
			}
			set
			{
				if ((this._date_demande != value))
				{
					this.Ondate_demandeChanging(value);
					this.SendPropertyChanging();
					this._date_demande = value;
					this.SendPropertyChanged("date_demande");
					this.Ondate_demandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personne_demande", Storage="_personne", ThisKey="id_pers", OtherKey="id", IsForeignKey=true)]
		public personne personne
		{
			get
			{
				return this._personne.Entity;
			}
			set
			{
				personne previousValue = this._personne.Entity;
				if (((previousValue != value) 
							|| (this._personne.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._personne.Entity = null;
						previousValue.demande.Remove(this);
					}
					this._personne.Entity = value;
					if ((value != null))
					{
						value.demande.Add(this);
						this._id_pers = value.id;
					}
					else
					{
						this._id_pers = default(int);
					}
					this.SendPropertyChanged("personne");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.historique")]
	public partial class historique
	{
		
		private int _id_d;
		
		private int _id_emp;
		
		private string _commentaire;
		
		public historique()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_d", DbType="Int NOT NULL")]
		public int id_d
		{
			get
			{
				return this._id_d;
			}
			set
			{
				if ((this._id_d != value))
				{
					this._id_d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_emp", DbType="Int NOT NULL")]
		public int id_emp
		{
			get
			{
				return this._id_emp;
			}
			set
			{
				if ((this._id_emp != value))
				{
					this._id_emp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_commentaire", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string commentaire
		{
			get
			{
				return this._commentaire;
			}
			set
			{
				if ((this._commentaire != value))
				{
					this._commentaire = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.personne")]
	public partial class personne : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _email;
		
		private string _password;
		
		private string _nom;
		
		private string _prenom;
		
		private string _role;
		
		private string _grade;
		
		private int _id_B;
		
		private System.Nullable<System.DateTime> _date_debut;
		
		private int _nbjour;
		
		private EntitySet<demande> _demande;
		
		private EntityRef<bureau> _bureau;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void OngradeChanging(string value);
    partial void OngradeChanged();
    partial void Onid_BChanging(int value);
    partial void Onid_BChanged();
    partial void Ondate_debutChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_debutChanged();
    partial void OnnbjourChanging(int value);
    partial void OnnbjourChanged();
    #endregion
		
		public personne()
		{
			this._demande = new EntitySet<demande>(new Action<demande>(this.attach_demande), new Action<demande>(this.detach_demande));
			this._bureau = default(EntityRef<bureau>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this.OngradeChanging(value);
					this.SendPropertyChanging();
					this._grade = value;
					this.SendPropertyChanged("grade");
					this.OngradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_B", DbType="Int NOT NULL")]
		public int id_B
		{
			get
			{
				return this._id_B;
			}
			set
			{
				if ((this._id_B != value))
				{
					if (this._bureau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_BChanging(value);
					this.SendPropertyChanging();
					this._id_B = value;
					this.SendPropertyChanged("id_B");
					this.Onid_BChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_debut", DbType="Date")]
		public System.Nullable<System.DateTime> date_debut
		{
			get
			{
				return this._date_debut;
			}
			set
			{
				if ((this._date_debut != value))
				{
					this.Ondate_debutChanging(value);
					this.SendPropertyChanging();
					this._date_debut = value;
					this.SendPropertyChanged("date_debut");
					this.Ondate_debutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbjour", DbType="Int NOT NULL")]
		public int nbjour
		{
			get
			{
				return this._nbjour;
			}
			set
			{
				if ((this._nbjour != value))
				{
					this.OnnbjourChanging(value);
					this.SendPropertyChanging();
					this._nbjour = value;
					this.SendPropertyChanged("nbjour");
					this.OnnbjourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="personne_demande", Storage="_demande", ThisKey="id", OtherKey="id_pers")]
		public EntitySet<demande> demande
		{
			get
			{
				return this._demande;
			}
			set
			{
				this._demande.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bureau_personne", Storage="_bureau", ThisKey="id_B", OtherKey="id", IsForeignKey=true)]
		public bureau bureau
		{
			get
			{
				return this._bureau.Entity;
			}
			set
			{
				bureau previousValue = this._bureau.Entity;
				if (((previousValue != value) 
							|| (this._bureau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bureau.Entity = null;
						previousValue.personne.Remove(this);
					}
					this._bureau.Entity = value;
					if ((value != null))
					{
						value.personne.Add(this);
						this._id_B = value.id;
					}
					else
					{
						this._id_B = default(int);
					}
					this.SendPropertyChanged("bureau");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_demande(demande entity)
		{
			this.SendPropertyChanging();
			entity.personne = this;
		}
		
		private void detach_demande(demande entity)
		{
			this.SendPropertyChanging();
			entity.personne = null;
		}
	}
}
#pragma warning restore 1591
